CREATE TABLE articles(
    id SERIAL NOT NULL PRIMARY KEY,
    url_key VARCHAR(256) NOT NULL UNIQUE,
    title VARCHAR(256) NOT NULL,
    author VARCHAR(256) NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    create_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION set_update_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.update_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER articles_update_at BEFORE UPDATE ON articles
FOR EACH ROW
EXECUTE PROCEDURE set_update_at();
